### ISSUE TITLE
Meeting Minutes for Week 7-8

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/fixml#148]
## Sprint Planning - 2024-06-10 Week 7

 - [x] #152
   - after merging #134 
     - only contain the json exporting
   - will create another PR to work on quarto template
 - [x] #133 
   - modify the analysis code to read the json
   - change the plot: vertical --> horizontal, ID --> Title
 - [x] (Presentation) Need outline on what problem we are looking at -> show the graph -> point out the evidence
 - [x] (Presentation) Further breakdown the confusion matrix by checklist item/repo
 - [x] ask Simon about forking / mirroring of our project if we change name  

## 2024-06-17 Week 8
 - [x] #160
 - [x] re-run 30 times on openja repo
   - Orix and Yingzi to review the current PRs and make sure the system logic is finalized
     - Orix: the response schema will not change
   - Tony to check with Simon if he is okay to spend another $36 for us to re-run
   - John to run on his computer
 - [x] (Optional, week 9) Write docstrings for our system's functions (incl. test function)
 - [x] (Optional, week 9) Write more (our system's) test functions
 - [x] #155
   - develop jinja template
   - generate .qmd as output
 - [x] #162
   - Add the unit for the score in evaluation report, e.g. score: 2.5/7 items
     - include a percentage: "2.5 items are satisfied out of 7 (34%)"
 - [x] #151
   - [x] #156 
   - [x] #166
   - [x] #167
   - [x] to ask Tiff and Simon if they prefer to publish the fixml to UBC / their PyPI account
 - [x] #163
 - [x] #97 
   - Yingzi is working on this
   - John, Tony, Orix to review it and update the technical instruction
 - [x] #98 
   - Tony to have a final look on it
   - could consider removing all archive/ and .ipynb after final presentation
   - will review before we submit our draft of data product
 - [x] #170
   - Potential issues about our system to be stated in the final report:
   - probably there is checklist item issue that requires improvement
   - probably there is structure issue for the repo
   - Add a conclusion whether we/users should trust our result in the Final Presentation based on the above methods
 - Will have a separate presentation with Dr Rohan Alexander in June 24/25th morning

### Future direction
 - Add checklist items
 - Prompt improvement by instructing GPT to distinguish standard case, edge case and error handling
 - To consider parallelising multiple API calls to speed up
 - Generate `get_openai_callback` to other LLM model in `src/test_creation/modules/workflow/runners/evaluator.py`
 - Consider including good test examples and repo example with ground truth as a context for GPT
 - add a hyperlink to go to the part of the code that is relevant to the missing test (require taking project code base as a context)
 - (Good to have/Future Dev) How to guide users for consistent writing of effective Requirements
   - guideline to standardize the language; 2) refine the Requirement more based on consistency evaluation
 - The test generator should focus on non-satisfying items
   - (good to have) based on the evaluation report and user input in the ML function(s) script files, add functionality to generate ref test cases for the non-satisfying items for that ML function(s)
 - (Not critical, Good to have) Containerize the package to include non-Python package dependencies
 - (Good to have)Add Experiment Github issue for improvement, e.g. few shot learning
 - (Good to have) write blog post to be posted in UBC MDS website

**Comment by tonyshumlh** [comment]
Partner Meeting Week 8 - 21/06/2024
- [ ] README -> environment.yaml vs .yml
- [ ] print out `help` content when --help instead of vim
- (Create Issue) password manager tool to manage OpenAI API key (e.g. KeePassXC package https://github.com/keepassxreboot/keepassxc)
- [ ] clearer instruction for creating `.env`
- [ ] Add a simple doc on how to set up OpenAI API key before using the tool
- [ ] For command line in README, use \ to separate long line
- [ ] Add/revise the `fixml report` command to transform and export from JSON responses to report 
- [ ] Add proper document, e.g. ReadTheDoc
- [ ] Separate the hosting of Report HTML and Documentation HTML: 
    - Report HTML: Github page, using branch gh-pages https://quarto.org/docs/publishing/github-pages.html#source-branch
    - Documentation HTML: use /docs 
- [ ] Move fixml repo to new Org out of UBC-MDS!!!

**Comment by JohnShiuMK** [comment]
- remove $ in the instruction
 - cd the repository
 - environment.yml
 - print the help to the terminal in terms of less
 - consider encrypted using KeePassXC to store the api key
 - (John's comment) export .env api key in the instruction
 - OPENAI_API_KEY="YOUR_API_KEY"
 - specify API key permissions (communicate with Simon)

**Comment by JohnShiuMK** [comment]
Orix:
 - Final report diagram
 - README
 - ReadtheDoc
 - Packaging
 - Write more tests

John:
 - github page
 - update plots
 - approve PR

Tony:
 - Final report

**Comment by jinyz8888** [comment]
@JohnShiuMK @SoloSynth1 @tonyshumlh the final report can't be accessed through the link <https://ubc-mds.github.io/fixml/report>
<img width="1014" alt="image" src="https://github.com/UBC-MDS/fixml/assets/108684429/935666de-661a-4341-8538-fb96d7d08884">

**Comment by JohnShiuMK** [comment]
done, close
